apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.name" . }}-database
spec:
  selector:
    app: database
  ports:
  - protocol: TCP
    port: {{ .Values.database.port }}
    targetPort: {{ .Values.database.port }}
  clusterIP: None
