apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-app.name" . }}-frontend
  labels:
    {{ include "web-app.labels" . }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.frontend.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.frontend.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
