apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web-app.name" . }}-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/issuer: "{{ .Values.tlsIssuer.name }}"
spec:
  rules:
  - host: {{ .Values.frontend.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "web-app.name" . }}-frontend
            port:
              number: 80
  tls:
  - hosts:
    - {{ .Values.frontend.ingress.host }}
    secretName: {{ .Values.frontend.ingress.tlsSecret }}
