apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.name" . }}-frontend
  labels:
    {{ include "web-app.labels" . }}
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.frontend.port }}
  type: ClusterIP
