apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.name" . }}-backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.backend.port }}
  type: ClusterIP
